repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: check-toml
          - id: name-tests-test
            args: [--pytest-test-first]
          - id: pretty-format-json
            args: [--autofix]
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/oxsecurity/megalinter
      rev: v6.8.0
      hooks:
        - id: megalinter-incremental
          stages:
            - commit
        - id: megalinter-full
          stages:
            - push
    - repo: local
      hooks:
          - id: pytest-check
            name: pytest-check
            entry: pytest
            language: system
            pass_filenames: false
            always_run: true

ci:
  skip: [pytest-check]
