name: Pytest
on:
  push:
    paths: ["**.py"]

  pull_request:
    paths: ["**.py"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-pretty
    - name: Test with pytest
      run: |
        pytest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3