name: Check requirements
on:
  push:
    paths: ["*requirements.txt", "pyproject.toml"]

  pull_request:
    paths: ["*requirements.txt", "pyproject.toml"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies from txt files
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install -r doc-requirements.txt
    - name: Install dependencies from pyproject.toml file
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install .
        pip install .[dev]
        pip install .[docs]
